services:
  cyber-esteban:
    container_name: cyber-esteban
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../.env:/app/.env
    networks:
      - database2_localdev

networks:
  database2_localdev:
    external: true
