name: Build and Push ARM64 Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_UN }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Build and push
        run: |
          docker build -t ghcr.io/database-sabermetrics/cyber-esteban:latest .
          docker push ghcr.io/database-sabermetrics/cyber-esteban:latest
